"""
Django settings for faction_store project.

Generated by 'django-admin startproject' using Django 6.0.3.
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'dev-only-secret-key-change-before-production',
)

DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get(
        'DJANGO_ALLOWED_HOSTS',
        'localhost,127.0.0.1,.vercel.app',
    ).split(',')
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Custom Faction Store Apps
    'accounts.apps.AccountsConfig',
    'products.apps.ProductsConfig',
    'cart.apps.CartConfig',
    'orders.apps.OrdersConfig',
    'payments.apps.PaymentsConfig',
    'reviews.apps.ReviewsConfig',
    'wishlist.apps.WishlistConfig',
    'contacts.apps.ContactsConfig',
    'dashboard.apps.DashboardConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'faction_store.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Global context processor for store settings and cart/wishlist count
                'dashboard.context_processors.store_settings',
                'cart.context_processors.cart_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'faction_store.wsgi.application'


# Database — PostgreSQL
# Set DATABASE_URL in your environment (works with Neon, Supabase, Railway, local Postgres, etc.)
# Format: postgres://USER:PASSWORD@HOST:PORT/DBNAME
#
# Fallback: set individual DB_* env vars for local development.
DATABASE_URL = os.environ.get('DATABASE_URL', '').strip()

# Detect serverless environment (Vercel, AWS Lambda)
IS_SERVERLESS = 'VERCEL' in os.environ or 'AWS_LAMBDA_FUNCTION_NAME' in os.environ

if DATABASE_URL:
    # Supabase Connection Pooler optimization:
    # Port 5432 is Session mode (limited to 15 clients -> raises EMAXCONNSESSION when multiple requests run).
    # Port 6543 is Transaction mode (PgBouncer/Supavisor -> supports thousands of concurrent serverless clients).
    if 'pooler.supabase.com' in DATABASE_URL and ':5432' in DATABASE_URL:
        DATABASE_URL = DATABASE_URL.replace(':5432', ':6543')

    # In serverless environments (e.g. Vercel) or when using poolers, connections should not be kept
    # open (conn_max_age=0) so frozen lambda containers release Supabase connections immediately.
    conn_max_age = int(os.environ.get('CONN_MAX_AGE', 0 if (IS_SERVERLESS or 'pooler.supabase.com' in DATABASE_URL) else 60))

    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=conn_max_age,
            conn_health_checks=True,
        )
    }

    # Disable server-side cursors for Supabase pooler / PgBouncer transaction mode
    if 'pooler.supabase.com' in DATABASE_URL or str(DATABASES['default'].get('PORT')) == '6543':
        DATABASES['default']['DISABLE_SERVER_SIDE_CURSORS'] = True
else:
    db_engine = os.environ.get('DB_ENGINE', '').lower()
    if db_engine == 'postgresql' or 'DB_NAME' in os.environ:
        db_host = os.environ.get('DB_HOST', 'localhost')
        db_port = os.environ.get('DB_PORT', '5432')
        if 'pooler.supabase.com' in db_host and db_port == '5432':
            db_port = '6543'

        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': os.environ.get('DB_NAME', 'embro_store'),
                'USER': os.environ.get('DB_USER', 'postgres'),
                'PASSWORD': os.environ.get('DB_PASSWORD', ''),
                'HOST': db_host,
                'PORT': db_port,
                'CONN_MAX_AGE': 0 if IS_SERVERLESS else 60,
            }
        }
        if 'pooler.supabase.com' in db_host or str(db_port) == '6543':
            DATABASES['default']['DISABLE_SERVER_SIDE_CURSORS'] = True
    else:
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}
  

# Media files (Uploaded images/profile pictures)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get('CSRF_TRUSTED_ORIGINS', 'https://*.vercel.app,https://embrostore.vercel.app').split(',')
    if origin.strip()
]
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Custom Authentication Settings
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'products:home'
LOGOUT_REDIRECT_URL = 'products:home'

# Console Email Backend for local development (Password Resets, Email Verification)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'support@embrostore.com'
