# Generated by Django 6.0.8 on 2026-09-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_dashboardwidget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='address',
            field=models.TextField(default='123 Embro Ave, New York, NY 10001'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='contact_email',
            field=models.EmailField(default='support@embrostore.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='settings',
            name='store_name',
            field=models.CharField(default='Embro Store', max_length=100),
        ),
    ]
