# Generated by Django 6.0.3 on 2026-06-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Faction Store', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('contact_email', models.EmailField(default='support@factionstore.com', max_length=254)),
                ('contact_phone', models.CharField(default='+1 234 567 8900', max_length=20)),
                ('address', models.TextField(default='123 Fashion Ave, New York, NY 10001')),
                ('facebook_url', models.URLField(blank=True, default='https://facebook.com')),
                ('instagram_url', models.URLField(blank=True, default='https://instagram.com')),
                ('twitter_url', models.URLField(blank=True, default='https://twitter.com')),
            ],
            options={
                'verbose_name': 'Store Setting',
                'verbose_name_plural': 'Store Settings',
            },
        ),
    ]
