# Generated by Django 6.0.3 on 2026-07-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('widget_type', models.CharField(choices=[('CARD', 'Stat Card'), ('CHART', 'Chart Widget'), ('CUSTOM', 'Custom HTML Block')], default='CARD', max_length=20)),
                ('value_override', models.CharField(blank=True, max_length=100, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=250, null=True)),
                ('icon', models.CharField(default='fas fa-chart-bar', max_length=100)),
                ('text_color', models.CharField(default='#ffffff', max_length=50)),
                ('bg_color', models.CharField(default='rgba(18, 18, 22, 0.55)', max_length=100)),
                ('border_color', models.CharField(default='rgba(255, 255, 255, 0.08)', max_length=100)),
                ('chart_type', models.CharField(blank=True, choices=[('PIE', 'Pie Chart'), ('BAR', 'Bar Chart'), ('LINE', 'Line Chart'), ('AREA', 'Area Chart')], max_length=20, null=True)),
                ('colors_json', models.TextField(default='["#d4af37", "#ffaa00", "#3b82f6", "#10b981", "#ef4444", "#a855f7"]')),
                ('legend_visible', models.BooleanField(default=True)),
                ('labels_json', models.TextField(blank=True, null=True)),
                ('refresh_interval', models.IntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=0)),
                ('custom_html', models.TextField(blank=True, null=True)),
                ('custom_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-is_pinned', 'position', 'id'],
            },
        ),
    ]
