# Generated by Django 6.0.3 on 2026-09-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='custom_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
