# Generated by Django 6.0.3 on 2026-09-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_cancel_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='custom_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
