# Generated by Django 6.0.3 on 2026-09-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_custom_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='custom_image',
            field=models.ImageField(blank=True, null=True, upload_to='custom_designs/'),
        ),
    ]
